source 'https://rubygems.org'

gem "concurrent-ruby", "1.1.9"
gem "minitest", "5.12.0"
gem "activesupport", "4.2.11.3"
gem "rexml", "3.2.0"
gem "xml-simple", "1.1.9"
gem 'net-http-server', '~> 0.2.3'
